services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgrespw
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
            
    mongodb:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=mongopw
        ports:
            - 27017:27017
        volumes: 
            - mongodata:/var/lib/mongodb/data
            
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672

    auction-svc:
        image: yasosim/auction-svc:latest
        build:
            context: .
            dockerfile: src/AuctionService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
            - IdentityServiceUrl=http://identity-svc
        ports:
            - 7001:80
        depends_on:
            - postgres
            - rabbitmq

    search-svc:
        image: yasosim/search-svc:latest
        build:
            context: .
            dockerfile: src/SearchService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - RabbitMq__Host=rabbitmq
            - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
            - AuctionServiceUrl=http://auction-svc
        ports:
            - 7002:80
        depends_on:
            - mongodb
            - rabbitmq

    identity-svc:
        image: yasosim/identity-svc:latest
        build:
            context: .
            dockerfile: src/IdentityService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=t
            - ASPNETCORE_URLS=http://+:80
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
        ports:
            - 5000:80
        depends_on:
            - postgres
            
    gateway-svc:
        image: yasosim/gateway-svc:latest
        build:
            context: .
            dockerfile: src/gatewayService/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+:80
        ports:
            - 6001:80

volumes:
    pgdata:
    mongodata: